import streamlit as st

st.title('Additional Resources')

st.header('Project Videos')
st.markdown("**Technovation Girls 2024 Project Videos**")
st.markdown("Pitch Video: %s" % "https://youtu.be/CDgDIT0llpM")
st.markdown("Demo Video: %s" % "https://youtu.be/Im4Lpc6iiSM")

st.header('Dataset Sources')
st.markdown("1. %s" % "https://zenodo.org/records/5636429")
st.markdown("2. %s" % "https://www.atsdr.cdc.gov/placeandhealth/svi/data_documentation_download.html")

st.header('References')
st.markdown("[1] Congressional Research Service. (2023). Wildfire Statistics. https://sgp.fas.org/crs/misc/IF10244.pdf")
st.markdown("[2] Hatfield, M. (2001). Wildfire and Poverty An Overview of the Interactions Among Wildfires, Fire-Related Programs, and Poverty in the Western States The Center for Watershed and Community Health Prepared for the CWCH by ECONorthwest BACKGROUND AND ACKNOWLEDGMENTS. https://scholarsbank.uoregon.edu/xmlui/bitstream/handle/1794/2334/wild_pov.pdf")
st.markdown("[3] Davies, I. P., Haugo, R. D., Robertson, J. C., & Levin, P. S. (2018). The Unequal Vulnerability of Communities of Color to Wildfire. PLOS ONE, 13(11), e0205825. https://doi.org/10.1371/journal.pone.0205825")
st.markdown("[4] Flanagan, B. E., Gregory, E. W., Hallisey, E. J., Heitgerd, J. L., & Lewis, B. (2011). A Social Vulnerability Index for Disaster Management. Journal of Homeland Security and Emergency Management, 8(1). https://doi.org/10.2202/1547-7355.1792")
st.markdown("[5] Polletta, M. (n.d.). As wildfires get worse, who will be hit hardest? Impact on some groups will be “strikingly unequal,” study says. The Arizona Republic. Retrieved February 17, 2024, from https://www.azcentral.com/story/news/local/arizona/2018/11/21/extreme-wildfires-may-hit-vulnerable-people-hardest-study-suggests/2065682002/")
st.markdown("[6] Low-Income Communities Struggle To Recover After A Wildfire. (2018, September 19). NPR. https://www.npr.org/2018/09/19/647606049/low-income-communities-struggle-to-recover-after-a-wildfire.%20Accessed%2016%20Nov%202022")
st.markdown("[7] Hatfield, M. (2001). Wildfire and Poverty An Overview of the Interactions Among Wildfires, Fire-Related Programs, and Poverty in the Western States The Center for Watershed and Community Health Prepared for the CWCH by ECONorthwest BACKGROUND AND ACKNOWLEDGMENTS. https://scholarsbank.uoregon.edu/xmlui/bitstream/handle/1794/2334/wild_pov.pdf")
st.markdown("[8] Finney, M. (1998). FARSITE: Fire Area Simulator-Model Development and Evaluation. https://www.fs.usda.gov/rm/pubs/rmrs_rp004.pdf")
st.markdown("[9] Applying fire spread simulation over two study sites in California lessons learned and future plans | IEEE Conference Publication | IEEE Xplore. (n.d.). Ieeexplore.ieee.org. Retrieved February 17, 2024, from https://ieeexplore.ieee.org/document/4423478")
st.markdown("[10] Radke, D., Hessler, A., & Ellsworth, D. (n.d.). FireCast: Leveraging Deep Learning to Predict Wildfire Spread. https://www.ijcai.org/Proceedings/2019/0636.pdf")
st.markdown("[11] Ding, Y., Wang, M., Fu, Y., Zhang, L., & Wang, X. (2023). A Wildfire Detection Algorithm Based on the Dynamic Brightness Temperature Threshold. Forests, 14(3), 477. https://doi.org/10.3390/f14030477")
st.markdown("[12] Ghorbanzadeh, O., Blaschke, T., Gholamnia, K., & Aryal, J. (2019). Forest Fire Susceptibility and Risk Mapping Using Social/Infrastructural Vulnerability and Environmental Variables. Fire, 2(3), 50. https://doi.org/10.3390/fire2030050")
st.markdown("[13] Hwang, S. N., & Meier, K. (2022). Associations between Wildfire Risk and Socio-Economic-Demographic Characteristics Using GIS Technology. Journal of Geographic Information System, 14(05), 365–388. https://doi.org/10.4236/jgis.2022.145020")
st.markdown("[14] Singla, S., Mukhopadhyay, A., Wilbur, M., Diao, T., Gajjewar, V., Eldawy, A., Kochenderfer, M., Shachter, R., & Dubey, A. (n.d.). WildfireDB: An Open-Source Dataset Connecting Wildfire Spread with Relevant Determinants. Retrieved February 17, 2024, from https://datasets-benchmarks-proceedings.neurips.cc/paper_files/paper/2021/file/3fe94a002317b5f9259f82690aeea4cd-Paper-round2.pdf")
st.markdown("[15] NASA VIIRS Land Science Investigator Processing System (SIPS) Visible Infrared Imaging Radiometer Suite (VIIRS) 375 m & 750 m Active Fire Products Product User’s Guide Version 1.4. (2018). https://viirsland.gsfc.nasa.gov/PDF/VIIRS_activefire_User_Guide.pdf")
st.markdown("[16] Ryan, K. C., & Opperman, T. S. (2013). LANDFIRE – A national vegetation/fuels database for use in fuels treatment, restoration, and suppression planning. Forest Ecology and Management, 294, 208–216. https://doi.org/10.1016/j.foreco.2012.11.003")
st.markdown("[17] Meteostat - Historical Weather and Climate Data. (n.d.). Meteostat.net. https://meteostat.net/en")
st.markdown("[18] CDC SVI Data and Documentation Download | Place and Health | ATSDR. (2020, October 15). www.atsdr.cdc.gov. https://www.atsdr.cdc.gov/placeandhealth/svi/data_documentation_download.html")
st.markdown("[19] Form 477 Census Tract Information | Federal Communications Commission. (n.d.). Www.fcc.gov. Retrieved February 17, 2024, from https://www.fcc.gov/general/form-477-census-tract-information#:~:text=A%20census%20tract%20FIPS%20code")
st.markdown("[20] US EPA. (2019, August 13). Health Effects Attributed to Wildfire Smoke. US EPA. https://www.epa.gov/wildfire-smoke-course/health-effects-attributed-wildfire-smoke")
st.markdown("[21] How Bad Is Wildfire Smoke for Your Health? (n.d.). Yale Medicine. https://www.yalemedicine.org/news/how-bad-is-wildfire-smoke-for-your-health")
st.markdown("[22] Modaresi Rad, A., Abatzoglou, J. T., Fleishman, E., Mockrin, M. H., Radeloff, V. C., Pourmohamad, Y., Cattau, M., Johnson, J. M., Higuera, P., Nauslar, N. J., & Sadegh, M. (2023). Social vulnerability of the people exposed to wildfires in U.S. West Coast states. Science Advances, 9(38), eadh4615. https://doi.org/10.1126/sciadv.adh4615")